apiVersion: apps/v1
kind: Deployment
metadata:
  name: rap
spec:
  template:
    spec:
      containers:
        - name: ampersand-rap
          env:
            - name: AMPERSAND_DBHOST
              value: rap-db-staging
            - name: RAP_HOST_NAME
              value: staging.rap.tarski.nl
            - name: RAP_STUDENT_PROTO_IMAGE
              value: ampersandtarski/rap4-student-prototype:staging-latest
