apiVersion: apps/v1
kind: Deployment
metadata:
  name: rap
spec:
  selector:
    matchLabels:
      app: rap
  template:
    spec:
      containers:
        - name: ampersand-rap
          env:
            - name: AMPERSAND_DBHOST
              value: rap-db-staging
            - name: RAP_KUBERNETES_NAMESPACE
              value: rap-staging
            - name: RAP_STUDENT_PROTO_IMAGE
              value: ampersandtarski/rap4-student-prototype:2025-02-28
