apiVersion: apps/v1
kind: Deployment
metadata:
  name: rap
spec:
  template:
    spec:
      containers:
        - name: ampersand-rap
          image: ampersandtarski/ampersand-rap:2024-12-13
          env:
            - name: RAP_HOST_NAME
              value: rap.tarski.nl
