version: '3.7'

services:
  rap3:
    image: docker.pkg.github.com/AmpersandTarski/rap/RAP3:latest
    container_name: rap3
    build:
      context: .
      dockerfile: ./RAP3/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./volumes/rap3/log:/var/www/log
      - ./volumes/rap3/data:/var/www/data
      - ./volumes/rap3/scripts:/var/www/scripts
    networks:
      - rap3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "100"

  # demo application
  # enroll:
 
  db:
    restart: always
    image: ampersandtarski/rap3-db
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - rap3
      - db

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    networks:
      - db

  # vscode:
  #   image: codercom/code-server
  #   command: --password=zoepersecreet
  #   ports:
  #     - "8443:8443"
  #   volumes:
  #     - ./volumes/scripts:/var/www/html/RAP3/scripts

  # latex:
  #   image: thomasweise/docker-texlive-full
  #   networks:
  #     - rap3

networks:
  rap3:
  db: