services:
  rap4:
    labels:
      traefik.http.routers.rap4-insecure.middlewares: redirectToHttps@file,securityHeaders@file
      traefik.http.routers.rap4.tls.certresolver: letsencrypt
      traefik.http.routers.rap4.tls.options: safeTLSOptions@file
      traefik.http.routers.rap4.middlewares: securityHeaders@file
      traefik.http.routers.rap4.rule: Host(`rap.cs.ou.nl`)
  enroll:
    labels:
      traefik.http.routers.enroll-insecure.middlewares: redirectToHttps@file,securityHeaders@file
      traefik.http.routers.enroll.tls.certresolver: letsencrypt
      traefik.http.routers.enroll.tls.options: safeTLSOptions@file
      traefik.http.routers.enroll.middlewares: securityHeaders@file
      traefik.http.routers.enroll.rule: Host(`enroll.rap.cs.ou.nl`)
  phpmyadmin:
    labels:
      traefik.http.routers.phpmyadmin-insecure.middlewares: redirectToHttps@file,securityHeaders@file
      traefik.http.routers.phpmyadmin.tls.certresolver: letsencrypt
      traefik.http.routers.phpmyadmin.tls.options: safeTLSOptions@file
      traefik.http.routers.phpmyadmin.middlewares: securityHeaders@file
      traefik.http.routers.phpmyadmin.enroll.rule: Host(`phpmyadmin.rap.cs.ou.nl`)
