version: '3.7'
# to visualize this docker-compose.yml file, run:
#      docker run --rm -it --name dcv -v $(pwd):/input pmsipilot/docker-compose-viz render -f -m image docker-compose.yml
# run it literally (change NOTHING!) and expect the result in docker-compose.png

volumes:
  rap3-logs:
  rap3-data: 
  rap3-scripts:
  db-data:
  proxy-cert:

services:
  # the gatekeeper to the internet. It serves both http and https.
  proxy:
    build: ./HAProxy
    container_name: proxy
    restart: unless-stopped
    depends_on:
      - rap3
      - enroll
    networks:
      - rap3
      - enroll
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy-cert:/srv/is-certificate
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "100"
  rap3:
    image: ampersandtarski/ampersand-rap:latest
    container_name: rap3
    build:
      context: RAP3
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - AMP_PROTO_ENV_NAME=default # use configured environments (e.g. default, dev, prod)
    volumes:
      - rap3-logs:/var/www/log
      - rap3-data:/var/www/data
      - rap3-scripts:/var/www/data/scripts
    networks:
      - rap3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "100"

  # demo application Enrollment
  enroll:
    image: ampersandtarski/enroll:latest
    container_name: enroll
    build:
      context: Demos/Enroll
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - enroll
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "100"
 
  db:
    restart: always
    image: ampersandtarski/rap3-db
    volumes:
      - db-data:/var/lib/mysql
    container_name: rap3-db
    build:
      context: RAP3DB
    networks:
      - rap3
      - db
      - enroll

  phptools:
    image: phpmyadmin/phpmyadmin
    container_name: phptools
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - db

  # vscode:
  #   image: codercom/code-server
  #   command: --password=zoepersecreet
  #   ports:
  #     - "8443:8443"
  #   volumes:
  #     - ./volumes/scripts:/var/www/html/RAP3/data/scripts

networks:
  rap3:
  db:
  enroll: