version: '2'

services:
  rap3:
    restart: always
    image: ampersandtarski/rap3:latest
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./volumes/log:/var/www/html/RAP3/log
      - ./volumes/scripts:/var/www/html/RAP3/scripts
 
  db:
    restart: always
    image: ampersandtarski/rap3-db
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8080:80"
    links:
      - db
