version: '3'

services:
  rap3:
    restart: always
    image: ampersandtarski/ampersand-rap:latest
    ports:
      - "80:80"
    links:
      - db
      - latex
    volumes:
      - ./volumes/log:/var/www/html/RAP3/log
      - ./volumes/scripts:/var/www/html/RAP3/scripts
 
  db:
    restart: always
    image: ampersandtarski/rap3-db
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db

  vscode:
    image: codercom/code-server
    command: --password=zoepersecreet
    ports:
      - "8443:8443"
    volumes:
      - ./volumes/scripts:/var/www/html/RAP3/scripts

  latex:
    image: thomasweise/docker-texlive-full