apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: student-prototype
  name: student-prototype
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-prototype
  template:
    metadata:
      labels:
        app: student-prototype
    spec:
      containers:
        - image: ampersandtarski/rap4-student-prototype:2025-02-28
          name: rap4-student-prototype
          env:
            - name: RAP_DEPLOYMENT
              value: Kubernetes
