loggers:
  EXECENGINE:
    handlers: [error_log, stdout, stderr]
  IO:
    handlers: [error_log, stdout, stderr]
  API:
    handlers: [error_log, stdout, stderr]
  APPLICATION:
    handlers: [error_log, stdout, stderr]
  DATABASE:
    handlers: [error_log, stdout, stderr]
  CORE:
    handlers: [error_log, stdout, stderr]
  RULEENGINE:
    handlers: [error_log, stdout, stderr]
  TRANSACTION:
    handlers: [error_log, stdout, stderr]
  INTERFACING:
    handlers: [error_log, stdout, stderr]
  HOOKS:
    handlers: [error_log, stdout, stderr]
  FRONTEND:
    handlers: [error_log, stdout, stderr]
  PERFORMANCE:
    handlers: [error_log, stdout, stderr]
  EVALIDATOR:
    handlers: [error_log, stdout, stderr]
  ONIMEX:
    handlers: [error_log, stdout, stderr]
formatters:
handlers:
  stderr:
    class: Monolog\Handler\StreamHandler
    level: WARNING
    processors: []
    stream: php://stderr
  stdout:
    class: Monolog\Handler\StreamHandler
    level: INFO
    processors: []
    stream: php://stdout
  error_log_file:
    class: Ampersand\Log\RotatingFileHandler
    level: DEBUG
    maxFiles: 5
    filename: ./log/error.log
    processors: []
  error_log:
    class: Monolog\Handler\FingersCrossedHandler
    handler: error_log_file
    activationStrategy: ERROR
    bufferSize: 0
    bubble: true
    stopBuffering: true
    passthruLevel: WARNING
processors:
  web_processor:
    class: Monolog\Processor\WebProcessor
    serverData: null
    extraFields:
      ip: REMOTE_ADDR
      method: REQUEST_METHOD
      url: REQUEST_URI
  request_id_processor:
    class: Ampersand\Log\RequestIDProcessor