apiVersion: apps/v1
kind: Deployment
metadata:
  name: rap
spec:
  template:
    spec:
      containers:
        - name: ampersand-rap
          env:
            - name: RAP_HOST_NAME
              value: staging.rap.tarski.nl