apiVersion: apps/v1
kind: Deployment
metadata:
  name: rap
spec:
  template:
    spec:
      containers:
        - name: ampersand-rap
          image: ampersandtarski/ampersand-rap:staging-latest
          env:
            - name: RAP_HOST_NAME
              value: staging.rap.cs.ou.nl