apiVersion: apps/v1
kind: Deployment
metadata:
  name: enroll
spec:
  template:
    spec:
      containers:
        - name: enroll
          env:
            - name: RAP_HOST_NAME
              value: enroll.dev.rap.tarski.nl