apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-prototype
spec:
  selector:
    matchLabels:
      app: student-prototype
  template:
    spec:
      containers:
        - image: ampersandtarski/rap4-student-prototype:2025-02-28
          name: rap4-student-prototype
          imagePullPolicy: Never
