apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-prototype
spec:
  template:
    spec:
      containers:
        - image: ampersandtarski/rap4-student-prototype:2024-12-13
          name: rap4-student-prototype
          imagePullPolicy: Never
