# # Role that is used to give a pod elevated rights in the Kubernetes cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elevated-rights-rolebinding
subjects:
  - kind: ServiceAccount
    name: elevated-rights-service-account
    namespace: rap-production