apiVersion: apps/v1
kind: Deployment
metadata:
  name: rap
spec:
  template:
    spec:
      containers:
        - name: ampersand-rap
          env:
            - name: AMPERSAND_DBHOST
              value: rap-db-production
            - name: RAP_KUBERNETES_NAMESPACE
              value: rap-production
            - name: RAP_STUDENT_PROTO_IMAGE
              value: ampersandtarski/rap4-student-prototype:production-latest
