apiVersion: v1
data:
  AMPERSAND_DBHOST: rap-db
  AMPERSAND_DBNAME: rap
  AMPERSAND_DEBUG_MODE: "true"
  AMPERSAND_LOG_CONFIG: logging.yaml
  AMPERSAND_PRODUCTION_MODE: "false"
  AMPERSAND_SERVER_URL: https://localhost
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rap-config
  namespace: rap
