settings:
  OAuthLogin.redirectAfterLogin: https://rap.cs.ou.nl/#/redirect-after-login
  OAuthLogin.redirectAfterLoginFailure: https://rap.cs.ou.nl
  OAuthLogin.identityProviders: 
    linkedin:
      name: LinkedIn
      logoUrl: app/ext/OAuthLogin/images/logo-linkedin.png
      authBase: https://www.linkedin.com/uas/oauth2/authorization
      redirectUrl: https://rap.cs.ou.nl/api/v1/oauthlogin/callback/linkedin
      clientId: 86s07m9hyin5fg
      clientSecret: wJHIRIQms5d2Sx1C
      tokenUrl: https://www.linkedin.com/uas/oauth2/accessToken
      apiUrl: https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))
      scope: r_emailaddress
      state: 4b253460f09386c8a5f42dfec2522ecf2d0083e25b2284806af0f1c444b62c37 # A unique string value of your choice that is hard to guess. Used to prevent CSRF
    github:
      name: GitHub
      logoUrl: app/ext/OAuthLogin/images/logo-github.png
      authBase: https://github.com/login/oauth/authorize
      redirectUrl: https://ketenstandaard.semantic-treehouse.nl/api/v1/oauthlogin/callback/github
      clientId: c5a0bae9b2a78e478346
      clientSecret: 6ab971bc6b1e34cc9b1b8662005586c635c7a067
      tokenUrl: https://github.com/login/oauth/access_token
      apiUrl: https://api.github.com/user/emails
      scope: user:email
      state: 4b253460f09386c8a5f42dfec2522ecf2d0083e25b2284806af0f1c444b62c37 # A unique string value of your choice that is hard to guess. Used to prevent CSRF
    # google:
    #   name: Google
    #   logoUrl: app/ext/OAuthLogin/images/logo-google.png
    #   authBase: https://accounts.google.com/o/oauth2/auth
    #   redirectUrl: https://rap.cs.ou.nl/api/v1/oauthlogin/callback/google
    #   clientId: 
    #   clientSecret: 
    #   tokenUrl: https://accounts.google.com/o/oauth2/token
    #   apiUrl: https://www.googleapis.com/userinfo/v2/me
    #   scope: https://www.googleapis.com/auth/userinfo.email
    #   state: 4b253460f09386c8a5f42dfec2522ecf2d0083e25b2284806af0f1c444b62c37 # A unique string value of your choice that is hard to guess. Used to prevent CSRF