apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: student-prototype
  name: student-prototype
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-prototype
  template:
    metadata:
      labels:
        app: student-prototype
    spec:
      containers:
        - image: ampersandtarski/rap4-student-prototype:v1.2.0
          name: rap4-student-prototype          
