apiVersion: apps/v1
kind: Deployment
metadata:
  name: rap
spec:
  selector:
    matchLabels:
      app: rap
  template:
    spec:
      containers:
        - name: ampersand-rap
          image: ampersandtarski/ampersand-rap:2025-02-28
          env:
            - name: RAP_HOST_NAME
              value: dev.rap.tarski.nl
