# Tempplate variables and secrets from environment ${ENVIRONMENT_NAME}:
#   DOMAIN_NAME: ${DOMAIN_NAME}
#   NAMESPACE_NAME: ${NAMESPACE_NAME}
#   LETSENCRYPT_PRIVATE_KEY: ${LETSENCRYPT_PRIVATE_KEY}
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: administration-configmap
  namespace: ${NAMESPACE_NAME}
data:
  DISABLE_DB_INSTALL: "true"
  AMPERSAND_PRODUCTION_MODE: "true"
