# Tempplate variables:
#   LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
#   LETSENCRYPT_PRIVATE_KEY: ${LETSENCRYPT_PRIVATE_KEY}
#
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ${LETSENCRYPT_EMAIL}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: ${LETSENCRYPT_PRIVATE_KEY}
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx
