# Tempplate variables:
#   DOMAIN_NAME: ${DOMAIN_NAME}
#   NAMESPACE_NAME: ${NAMESPACE_NAME}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rap
  name: rap
  namespace: ${NAMESPACE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rap
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rap
    spec:
      serviceAccountName: elevated-rights-service-account
      containers:
        - image: ampersandtarski/ampersand-rap:2023-04-28
          name: ampersand-rap
          ports:
            - containerPort: 80
          resources: {}
          env:
            - name: AMPERSAND_DBHOST
              value: rap-db
            - name: AMPERSAND_DBNAME
              value: rap
            - name: AMPERSAND_DEBUG_MODE
              value: "true"
            - name: AMPERSAND_LOG_CONFIG
              value: logging.yaml
            - name: AMPERSAND_SERVER_URL
              value: https://localhost
            - name: RAP_DEPLOYMENT
              value: Kubernetes
            - name: RAP_HOST_NAME
              value: ${DOMAIN_NAME}
            - name: RAP_KUBERNETES_NAMESPACE
              value: ${NAMESPACE_NAME}
            - name: RAP_STUDENT_PROTO_IMAGE
              value: ampersandtarski/rap4-student-prototype:v1.2.0
            - name: RAP_STUDENT_PROTO_LOG_CONFIG
              value: logging.yaml
          envFrom:
            - configMapRef:
                name: administration-configmap
            - secretRef:
                name: db-secrets
