apiVersion: apps/v1
kind: Deployment
metadata:
  name: enroll
spec:
  selector:
    matchLabels:
      app: enroll
  template:
    spec:
      containers:
        - name: enroll
          env:
            - name: RAP_HOST_NAME
              value: enroll.rap.tarski.nl
