apiVersion: apps/v1
kind: Deployment
metadata:
  name: rap
spec:
  selector:
    matchLabels:
      app: rap
  template:
    spec:
      containers:
        - name: ampersand-rap
          image: ampersandtarski/ampersand-rap:2025-02-28
          imagePullPolicy: Always
          env:
            - name: RAP_HOST_NAME
              value: staging.rap.tarski.nl
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
