name: CICD Pipeline  

on:
  push:
    branches: 
      - development
      - 'feature/**'
  pull_request:
    branches: 
      - development
      - 'feature/**'
  workflow_dispatch:

env:
  workflow_variable: "workflow value"  

jobs:
  
  Local:
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: 'Local${{ github.actor }}'

  Development:
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Development

  Staging:
    needs: Development
    if: github.ref_name == 'development'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Staging
