name: CICD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  workflow_variable: "workflow value"

jobs:
  Local:
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: "Local${{ github.actor }}"

  Staging:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Staging
