name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "issue/**"
  pull_request:
  workflow_dispatch:

jobs:
  Local:
    if: startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: "Local${{ github.actor }}"

  Development:
    if: startsWith(github.ref_name, 'issue/')
    # if: github.ref_name == 'main'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Development

  Staging:
    if: github.ref_name == 'main'
    needs: Development
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Staging

  Production:
    if: github.ref_name == 'main'
    needs: Staging
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Production
