name: CICD Pipeline

on:
  push:
    branches: 
      - development
      - 'feature/**'
  pull_request:
    branches: 
      - development
      - 'feature/**'

env:
  workflow_variable: "workflow value"  

jobs:
  
  Development:
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      env_name: Development

  Staging:
    if: github.ref_name == 'development'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      env_name: Staging
