name: CICD Pipeline

on:
  push:
    branches: 
      - development
      - 'feature/**'
  pull_request:
    branches: 
      - development
      - 'feature/**'
  workflow_dispatch:


jobs:

  Local:
    if: startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: 'Local${{ github.actor }}'

  Development:
    if: github.ref_name == 'development'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Development

  Staging:
    needs: Development
    if: github.ref_name == 'development'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Staging
