name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
      - "issue/**"
  pull_request:
  workflow_dispatch:

jobs:
  Local:
    if: startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: "Local${{ github.actor }}"
    secrets: inherit

  Development:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Development
    secrets: inherit

  Staging:
    if: github.ref_name == 'main'
    needs: Development
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Staging
    secrets: inherit

  Production:
    if: github.ref_name == 'main'
    needs: Staging
    uses: ./.github/workflows/Deploy_workflow.yml
    with:
      environment_name: Production
    secrets: inherit
