name: Deploy workflow

on:
  workflow_call:
    inputs:
      environment_name:
        description: Name of the environment to which is deployed
        required: true
        type: string

jobs:
  CheckEnvironment:
    environment: "${{ inputs.environment_name }}"
    runs-on: ubuntu-latest
    outputs:
      environment-ok: ${{ steps.my-environment-check.outputs.defined }}
    steps:
      - name: Check for Environment availability
        id: my-environment-check
        # perform check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ vars.ENVIRONMENT_NAME }}" == ${{ inputs.environment_name }} ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi
  Build:
    environment: '${{ inputs.environment_name }}'
    needs: [CheckEnvironment]
    if: needs.CheckEnvironment.outputs.environment-ok == 'true'
    runs-on: ubuntu-latest
    env:
      ENROLL_NAME: ${{ vars.enroll_name }}
      RAP_NAME: ${{ vars.rap_name }}
      DOMAIN_NAME: ${{ vars.domain_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echoing variables
        run: |
          echo Echoing vars.enroll_name: ${{ vars.enroll_name }}
          echo Echoing vars.domain_name: ${{ vars.domain_name }}
