name: Deploy workflow

on:
  workflow_call:
    inputs:
      environment_name:
        description: Name of the environment to which is deployed
        required: true
        type: string

jobs:
  CheckEnvironment:
    environment: ${{ inputs.environment_name }}
    runs-on: ubuntu-latest
    outputs:
      environment-ok: ${{ steps.my-environment-check.outputs.defined }}
    steps:
      - name: Check for Environment availability
        id: my-environment-check
        # perform check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ vars.ENVIRONMENT_NAME }}" == ${{ inputs.environment_name }} ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi

  CheckRAP4USER:
    runs-on: ubuntu-latest
    outputs:
      hasChanged: ${{ steps.hasChanged.outputs.hasDiff }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: pwsh
        id: hasChanged
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under RAP4USER/ has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^RAP4USER/' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "hasDiff"
          echo "hasDiff=$HasDiff" >> $Env:GITHUB_OUTPUT

  CheckRAP4:
    runs-on: ubuntu-latest
    outputs:
      hasChanged: ${{ steps.hasChanged.outputs.hasDiff }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: pwsh
        id: hasChanged
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under RAP4/ has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^RAP4/' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "hasDiff"
          echo "hasDiff=$HasDiff" >> $Env:GITHUB_OUTPUT

  Build:
    environment: ${{ inputs.environment_name }}
    needs: [CheckEnvironment, CheckRAP4USER, CheckRAP4]
    if: ${{ needs.CheckEnvironment.outputs.environment-ok == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push RAP4USER
        uses: docker/build-push-action@v4
        if: ${{ needs.CheckRAP4USER.outputs.hasChanged == 'True' }}
        with:
          context: ./RAP4USER
          file: ./RAP4USER/Dockerfile
          push: true
          tags: |
            ampersandtarski/rap4-student-prototype:${{ inputs.environment_name }}-latest
            ampersandtarski/rap4-student-prototype:${{ inputs.environment_name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push RAP4
        uses: docker/build-push-action@v4
        # if: ${{ needs.CheckRAP4.outputs.hasChanged == 'True' }}
        with:
          context: ./RAP4
          file: ./RAP4/Dockerfile
          push: true
          tags: |
            ampersandtarski/ampersand-rap:${{ inputs.environment_name }}-latest
            ampersandtarski/ampersand-rap:${{ inputs.environment_name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    permissions: write-all
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OU_CLIENT_ID }}
          tenant-id: ${{ secrets.OU_TENANT_ID }}
          subscription-id: ${{ secrets.OU_SUBSCRIPTION_ID }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: kubernetes-tst
          cluster-name: ampersand-rap-aks-tst

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Update image
        id: update-image
        shell: bash
        run: |
          kubectl set image deployment/rap-${{ inputs.environment_name }} ampersand-rap=ampersandtarski/ampersand-rap:${{ inputs.environment_name }}-${{ github.sha }}

      # - name: Deploy to AKS
      #   id: deploy-aks
      #   uses: Azure/k8s-deploy@v4
      #   with:
      #     namespace: "rap-${{ inputs.environment_name }}"
      #     manifests: |
      #       deployment/resources/rap-deployment.yaml
      #     images: |
      #       ampersandtarski/ampersand-rap:${{ inputs.environment_name }}-${{ github.sha }}
