name: Deploy workflow

on:
  workflow_call:
    inputs:
      environmentName:
        description: Name of the environment to which is deployed
        required: true
        type: string
      context:
        description: Context and path for docker build
        required: true
        type: string
      deploymentName:
        description: Name of the deployment to change
        required: true
        type: string
      containerName:
        description: Name of the container to change
        required: true
        type: string
      imageName:
        description: Name of the image to change
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.context }}
          file: ./${{ inputs.context }}/Dockerfile
          push: true
          tags: |
            ampersandtarski/${{inputs.imageName}}:${{ inputs.environmentName }}-latest
            ampersandtarski/${{inputs.imageName}}:${{ inputs.environmentName }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    permissions: write-all
    environment: Production
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OU_CLIENT_ID }}
          tenant-id: ${{ secrets.OU_TENANT_ID }}
          subscription-id: ${{ secrets.OU_SUBSCRIPTION_ID }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: kubernetes-prd
          cluster-name: ampersand-rap-aks-prd

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Update image
        id: update-image
        shell: bash
        run: |
          kubectl set image deployment/${{inputs.deploymentName}}-${{inputs.environmentName}} ${{inputs.containerName}}=ampersandtarski/${{inputs.imageName}}:${{ inputs.environmentName }}-${{ github.sha }} -n rap-${{ inputs.environmentName }}
