# This is a basic workflow to help you get started with Actions

name: Deploy workflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      env_name:
        description: environment to deploy to
        required: true
        type: string

env:
  workflow_variable: "workflow value"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  EchoVariables:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}

    env:
      job_variable: "job value"  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      - name: Echoing variables
        env:
          step_variable: "step value"  
        run: |
          echo Echoing workflow_variable * $workflow_variable *
          echo Echoing job_variable * $job_variable * 
          echo Echoing step_variable * $step_variable * 
          echo Echoing github.actor * ${{ github.actor }} *
          echo Echoing github.base_ref * ${{ github.base_ref }} *
          echo Echoing github.ref_name * ${{ github.ref_name }} *
          echo Echoing github.repository * ${{ github.repository }} *
          echo Echoing github.run_id * ${{ github.run_id }} *
          echo Echoing github.workflow * ${{ github.workflow }} *
          echo Echoing vars.AVARIABLE * ${{ vars.AVARIABLE }} *
          echo Echoing secrets.ASECRET * ${{ secrets.ASECRET }} *
