name: Specflow tests

on:
  push:
    branches:
      - feature/Specflow-test-pipeline

jobs:
  Build_Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Update image
        id: update-image
        shell: bash
        run: |
          pd
          cwd
          ls
