name: Specflow tests

on:
  push:
    branches:
      - feature/Specflow-test-pipeline

jobs:
  Build_Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build docker
        id: update-image
        shell: bash
        run: |
          cd ./RAP4
          docker build -t ampersandtarski/ampersand-rap:dev-latest .
          cd ..
          cp .example.env .env
          docker compose build
          docker network create proxy
          docker network create rap_db
          docker compose up -d

      - name: Run tests
        uses: actions/cryptic-wizard/run-specflow-tests@v1.3.3
        with:
          test-assembly-path: Testing/SpecFlow/SpecFlowRAP/SpecFlowCalculator.Specs/
          test-assembly-dll: SpecFlowRAP.Specs.dll
          output-html: MyTestResults.html

        #   cd ../RAP4USER
        #   docker build -t ampersandtarski/rap4-student-prototype:dev-latest .
